# Generated by Django 5.1 on 2024-09-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_tracked_time_day_alter_tracked_time_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracked_time',
            old_name='app',
            new_name='apps',
        ),
    ]
