# Generated by Django 5.1 on 2024-09-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_trackedtime_delete_tracked_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedtime',
            name='day',
            field=models.IntegerField(default=7, editable=False),
        ),
    ]
