# Generated by Django 5.1 on 2024-09-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_trackedtime_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedtime',
            name='day',
            field=models.IntegerField(default=9, editable=False),
        ),
    ]
